version: '3.8'

services:
  backend:
    image: joedaneffiong/dream-vacation-backend:latest
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
    networks:
      - vacation-network

networks:
  vacation-network:
    driver: bridge