version: "3.8"

services:
  postgres:
    image: postgres:16
    container_name: dream-vacation-db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
    container_name: dream-vacation-backend
    environment:
      DATABASE_URL: ${DATABASE_URL}
      PORT: ${PORT}
      COUNTRIES_API_BASE_URL: ${COUNTRIES_API_BASE_URL}
      COUNTRIES_API_KEY: ${COUNTRIES_API_KEY}
    ports:
      - "3001:3001"
    depends_on:
      - postgres

  frontend:
    build:
      context: ./frontend
    container_name: dream-vacation-frontend
    environment:
      REACT_APP_API_URL: http://localhost:3001
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  postgres_data:
